CREATE DATABASE proyecto;
USE proyecto

CREATE TABLE INMUEBLE(
CveInmueble INT NOT NULL PRIMARY KEY,
NomInmueble VARCHAR(30) NOT NULL,
DirInmueble VARCHAR(50) NOT NULL,
TamInmueble INT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EVENTO(
CveEvento INT NOT NULL PRIMARY KEY,
NomEvento VARCHAR(30) NOT NULL,
FechaEvento DATE NOT NULL,

    sjdjadjsaj
TipoEvento VARCHAR (20) NOT NULL,
CveInmueble INT NOT NULL,
FOREIGN KEY (CveInmueble) REFERENCES INMUEBLE(CveInmueble)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE GENEROMUSICAL(
CveEvento INT NOT NULL,
GeneroMusic VARCHAR(15) NOT NULL,
PRIMARY KEY (CveEvento,GeneroMusic),
FOREIGN KEY (CveEvento) REFERENCES EVENTO(CveEvento)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ARTISTA(
CveArtista INT NOT NULL PRIMARY KEY,
NomArtista VARCHAR(30) NOT NULL,
GeneroArtista VARCHAR(15) NOT NULL,
EscenarioArtista VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE CASHLESS(
CveCash INT NOT NULL PRIMARY KEY,
Saldo INT NOT NULL,
ApPa VARCHAR(20),
ApMa VARCHAR(20),
NomP VARCHAR(30),
CveEvento INT NOT NULL,
FOREIGN KEY (CveEvento) REFERENCES EVENTO(CveEvento)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PERSONA(
CvePersona INT NOT NULL PRIMARY KEY,
ApPat VARCHAR(20) NOT NULL,
ApMat VARCHAR(20),
NomPila VARCHAR(20) NOT NULL,
Correo VARCHAR(25) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE COMPRA(
CveCompra INT NOT NULL PRIMARY KEY,
CveEvento INT NOT NULL,
CvePersona INT NOT NULL,
FOREIGN KEY (CveEvento) REFERENCES EVENTO(CveEvento)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CvePersona) REFERENCES PERSONA(CvePersona)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE BOLETO(
CveBoleto INT NOT NULL PRIMARY KEY,
NomEvento VARCHAR(30) NOT NULL,
NoAsiento INT,
TipoBoleto VARCHAR(20) NOT NULL,
Fecha DATE NOT NULL,
Seccion VARCHAR(10)
) ENGINE=InnoDB;

CREATE TABLE DETALLECOMPRA(
FecCompra DATE NOT NULL,
Monto INT NOT NULL,
Cantidad INT NOT NULL,
CveCompra INT NOT NULL,
CveBoleto INT NOT NULL,
PRIMARY KEY (FecCompra,CveCompra,CveBoleto),
FOREIGN KEY (CveCompra) REFERENCES COMPRA(CveCompra)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CveBoleto) REFERENCES BOLETO(CveBoleto)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ORGANIZACION(
CveOrga INT NOT NULL PRIMARY KEY,
NoEmpleados INT NOT NULL,
SupervisorOrg INT NOT NULL,
TipoOrg VARCHAR(15) NOT NULL,
EncargadosOrg INT NOT NULL,
CveInmueble INT NOT NULL,
FOREIGN KEY (CveInmueble) REFERENCES INMUEBLE(CveInmueble)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE EMPLEADO(
CveEmpleado INT NOT NULL PRIMARY KEY,
ApPa VARCHAR(20) NOT NULL,
ApMa VARCHAR(20) NOT NULL,
NomP VARCHAR(30) NOT NULL,
DirEmpleado VARCHAR(50) NOT NULL,
Cargo VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE TURNOS(
CveEmpleado INT NOT NULL,
TurnosEm VARCHAR(30) NOT NULL,
PRIMARY KEY (CveEmpleado,TurnosEm),
FOREIGN KEY (CveEmpleado) REFERENCES EMPLEADO(CveEmpleado)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PATROCINIO(
CvePatro INT NOT NULL PRIMARY KEY,
NomPat VARCHAR(30),
EmpresaCargo VARCHAR(30),
TipoPat VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE ACREDITACION(
CveAcre INT NOT NULL PRIMARY KEY,
Zona VARCHAR(20) NOT NULL,
TipoAcre VARCHAR(20) NOT NULL,
CvePersona INT NOT NULL,
FOREIGN KEY (CvePersona) REFERENCES PERSONA(CvePersona)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PUBLICIDAD(
CvePubli INT NOT NULL PRIMARY KEY,
NomPub VARCHAR(30) NOT NULL,
TipoPubl VARCHAR(20) NOT NULL,
EncargadiPub VARCHAR(30) NOT NULL,
CvePatro INT NOT NULL,
FOREIGN KEY (CvePatro) REFERENCES PATROCINIO(CvePatro)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ARTISTA_EVENTO(
CveArtista INT NOT NULL,
CveEvento INT NOT NULL,
Fecha DATE NOT NULL,
HORA TIME NOT NULL,
PRIMARY KEY (CveArtista,CveEvento),
FOREIGN KEY (CveArtista) REFERENCES ARTISTA(CveArtista)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CveEvento) REFERENCES EVENTO(CveEvento)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PATROCINADO(
CveInmueble INT NOT NULL,
CvePatro INT NOT NULL,
PRIMARY KEY (CveInmueble,CvePatro),
FOREIGN KEY (CveInmueble) REFERENCES INMUEBLE(CveInmueble)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CvePatro) REFERENCES PATROCINIO(CvePatro)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TRABAJA_EN(
CveOrga INT NOT NULL,
CveEmpleado INT NOT NULL,
PRIMARY KEY (CveOrga,CveEmpleado),
FOREIGN KEY (CveOrga) REFERENCES ORGANIZACION(CveOrga)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CveEmpleado) REFERENCES EMPLEADO(CveEmpleado)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=InnoDB;